### ISSUE TITLE
What about a small documentation ?

### ISSUE THREAD

**Issue by AlexiZ** [erichard/doctrine-pgsql-extension#1]
Hi Erwan, and welcome to GIthub !

What about adding a small documentation ?
I'll start with : 

- in your config.yml, add those lines under the `doctrine` entry (I've added a few of types that are not in your bundle but that would be useful) : 
```YAML
        types:
            translated: SiteBundle\DBAL\TranslatedType
            varchar_array: SiteBundle\DBAL\VarcharArrayType
            integer_array: SiteBundle\DBAL\IntegerArrayType
            boolean_array: SiteBundle\DBAL\BooleanArrayType
            daterange: SiteBundle\DBAL\DateRangeType
        mapping_types:
            jsonb: jsonb
            translated: translated
            daterange: daterange
```

I'll reply to this post to add the other elements. To be continued...
